### ISSUE TITLE
Windows resource window

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#130]
- [x] Core - #129
 - [x] Design
 - [x] Localized
 - Behavior:
   - [x] Keyboard control
   - [x] Accessibility
   - [x] Selection
 - Theming:
   - [x] Light themed
   - [x] Dark themed
   - [ ] High contrast

**Comment by vancura** [comment]
Windows Resource Window is very similar to the [Mac Resource Popover](https://github.com/xamarin/Xamarin.PropertyEditing/issues/131), with some UX changes due to typical behavior on the Windows platform.

Windows Resource Window opens in a window instead of a popover (as there's no standard popover mechanics on Windows). We also display an inline search field on top to filter table results. Selection switcher in the footer is nearly identical to Mac, except its visual treatment is more Windows-like (using radio boxes). The _Show Preview_ checkbox is used instead of an icon seen in the Mac popover.

<img width="625" alt="win resource selector popover colors 2x" src="https://user-images.githubusercontent.com/4982/35796902-511b3a84-0a5e-11e8-939e-8bc7baf87c6e.png">

Here, the _OK_ button is disabled, since no table row is selected. It will be enabled, as soon as a row is chosen:

<img width="625" alt="win resource selector popover colors selected 2x" src="https://user-images.githubusercontent.com/4982/35797049-c30b9d5a-0a5e-11e8-9d4c-877c55332321.png">

When _Show Preview_ checkbox is on, we display the preview panel on the left side. On Windows, we always show the preview pane on the left side (the side where the checkbox is located), as we use a window instead of a Mac-side popover (which is anchored to the side with the property pad).

<img width="886" alt="win resource selector popover colors preview 2x" src="https://user-images.githubusercontent.com/4982/35797118-fd5f4696-0a5e-11e8-8ba9-7f86d4100315.png">

Similar to the no-preview version above, _OK_ button is disabled. It's enabled as soon as a selection is made:

<img width="886" alt="win resource selector popover colors selected preview 2x" src="https://user-images.githubusercontent.com/4982/35797141-10a3c4de-0a5f-11e8-99b5-443705bad4a3.png">

Thoughts?
