### ISSUE TITLE
Mac resource window

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#131]
- [x] Core - #129
 - [x] Design
 - [x] Localized
 - Behavior:
   - [ ] Keyboard control
   - [ ] Accessibility
   - [ ] Selection
 - Theming:
   - [x] Light themed
   - [x] Dark themed
   - [x] High contrast

**Comment by vancura** [comment]
## Standard Property Pad with a tooltip

<img width="461" alt="mac resource selector 2x" src="https://user-images.githubusercontent.com/4982/35686245-1fa15d3e-076c-11e8-8237-1c98a0c77371.png">

## Selecting a color resource

- The headline in the popover contains _Color_ – that's when it's clear that only one type of the resource could be selected (color in this case).
- There's the _all/local/shared_ switch in the footer, which just filters the list to see the items based on the selection.
- Shared items are marked with an icon (also seen in the footer next to the _shared_ button)
- There's also a _Preview_ icon to toggle the preview pane (see below). Here it's not enabled, the icon is not highlighted.

<img width="628" alt="mac resource selector popover colors 2x" src="https://user-images.githubusercontent.com/4982/35686446-9227a08e-076c-11e8-9b46-f563b1ca83b5.png">

## Color resource is selected

- The headline in the popover still displays _Color_, since we don't allow to select anything but a color.
- The color resource is selected, so we need to mark the item in the table as selected (following Apple HIG, with white text and `~sel` icon, also with a white stroke around the color).
- The color is set in the property in the property pad.
- The user can now click anywhere, the popover hides and the new value remains in the property pad.

<img width="628" alt="mac resource selector popover colors selected 2x" src="https://user-images.githubusercontent.com/4982/35686590-e7668a9c-076c-11e8-8d54-fbcd6af4027e.png">

## Selecting a String resource

- The headline in the popover displays _String_ since we don't allow to select anything but a String.

<img width="628" alt="mac resource selector popover generic 2x" src="https://user-images.githubusercontent.com/4982/35689753-7c5d53cc-0774-11e8-9b72-5413c6cc53db.png">

## Selecting a generic resource

Since we allow to select one of many types of resources, we do a couple of things:

- The headline in the popover doesn't display any explicit resource type.
- The table contains a type rectangle too, so it's obvious what's the resource type.

<img width="628" alt="mac resource selector popover mixed 2x" src="https://user-images.githubusercontent.com/4982/35689846-b54088da-0774-11e8-9ae7-9d74589a8cec.png">

## Preview pane on – no color resource selected

<img width="758" alt="mac resource selector popover colors preview 2x" src="https://user-images.githubusercontent.com/4982/35689458-dd827b9c-0773-11e8-93fe-abb0839264b2.png">

## Preview pane on – a color resource selected

<img width="758" alt="mac resource selector popover colors selected preview 2x" src="https://user-images.githubusercontent.com/4982/35689503-f6007c6e-0773-11e8-811a-8c94bccac01b.png">

## Preview pane on – a bitmap resource is selected

<img width="758" alt="mac resource selector popover mixed preview 2x" src="https://user-images.githubusercontent.com/4982/35689559-1f237024-0774-11e8-99e4-49af426cdf32.png">

Thoughts?

**Comment by vancura** [comment]
## Left-hand preview

When the Property Pad is on the right side of the window (default in VS, VSMac, and Interactive), we can't show anything on the right side, as there might be the edge of the screen. Hence we need to show the preview on the left side, reversed.

<img width="725" alt="mac resource selector popover mixed preview left 2x" src="https://user-images.githubusercontent.com/4982/35732513-ea3b5682-0819-11e8-8da0-6a8fc1e3dabb.png">

**Comment by vancura** [comment]
## Dark theme:

<img width="628" alt="1mac resource selector popover colors selected dark 2x" src="https://user-images.githubusercontent.com/4982/35736575-d41dfabc-0828-11e8-960f-54339585005f.png">

<img width="758" alt="2mac resource selector popover colors preview dark 2x" src="https://user-images.githubusercontent.com/4982/35736580-d74c78a8-0828-11e8-8686-63da815c971f.png">

<img width="758" alt="3mac resource selector popover colors selected preview dark 2x" src="https://user-images.githubusercontent.com/4982/35736584-da1fd534-0828-11e8-891a-0148b547ead6.png">

<img width="725" alt="4mac resource selector popover mixed preview left dark 2x" src="https://user-images.githubusercontent.com/4982/35736588-dd015d90-0828-11e8-9e5a-3721cd732f84.png">

**Comment by ermau** [comment]
@vancura What's the text content for a preview of a gradient?

**Comment by vancura** [comment]
What about this?

<img width="725" alt="mac resource selector popover mixed preview left 2x" src="https://user-images.githubusercontent.com/4982/35862896-8427e5fe-0b4d-11e8-9d1e-f261ad9332b3.png">

It uses the same component as the _Brush Mac Editor_, just without border and interactive elements:

<img width="408" alt="mac inline gradient brush editor 2x" src="https://user-images.githubusercontent.com/4982/35524585-48d42b06-0522-11e8-83ee-09b5738296d8.png">

**Comment by vancura** [comment]
(EDIT: image above updated so it doesn't really contain _any_ interactive controls, active color in this case)

**Comment by CartBlanche** [comment]
@lewing So you colour picker i based off this?

**Comment by CartBlanche** [comment]
@vancura I've only just realised we need `resource-editor-16` versions of the `resource-editor-32` icons which support the `~sel` suffix for when the tab is selected and the various themed versions.
Its already in the code, we just need to create the icons and add them to the project.

**Comment by vancura** [comment]
All the icons are pushed at https://github.com/xamarin/Xamarin.PropertyEditing/commit/1604287b5b4149e8d3b4f694cc0b714a4abe3511.
