### ISSUE TITLE
Mac Object Editor

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#141]
Depends on #116

 - [x] Core
 - Editor:
   - [x] Design
   - [x] Localized
   - Behavior:
     - [x] Keyboard control
     - [x] Accessibility
     - [x] Selection
   - Theming:
     - [ ] Light themed
     - [ ] Dark themed
     - [ ] High contrast
   - States:
     - [ ] Error state
     - [ ] Bound state
     - [ ] Conflict state
     - [ ] Pending state

**Comment by vancura** [comment]
@ermau: What's this please, could you grab a screenshot from VS? I can't find any information in our docs.

**Comment by vancura** [comment]
## No effect applied

<img width="408" alt="mac object editor 2x" src="https://user-images.githubusercontent.com/4982/35871754-59755a4a-0b65-11e8-9c98-3fb054ff1897.png">

## Selecting an effect

<img width="408" alt="mac object editor new 2x" src="https://user-images.githubusercontent.com/4982/35871783-68b11f8a-0b65-11e8-9407-f8295c4e7a2a.png">

- see the naming of the effects, I've removed the _effect_ suffix (like _Drop shadow effect_) since we write that you're picking an effect in the headline, it's more noise than signal.
- also, see the footer with selector from the Resource popover/window. It's same, except it uses word _Effects_ instead of _Resources_.

## An effect is added

<img width="408" alt="mac object editor added 2x" src="https://user-images.githubusercontent.com/4982/35871916-c09efbc2-0b65-11e8-9a97-fb18dd1a321a.png">

- again, no need to write _Drop shadow effect_ in the property value, since the _Effect_ is written in the property title.
- see the expansion chevron.

## Expanded effect

<img width="408" alt="mac object editor added 2x-1" src="https://user-images.githubusercontent.com/4982/35871958-e11c170e-0b65-11e8-9a85-6a07d968882b.png">

## Selecting a different effect

<img width="442" alt="mac object editor added 2x-2" src="https://user-images.githubusercontent.com/4982/35871980-f3dc86a8-0b65-11e8-9007-454ef7ffc42b.png">

**Comment by ermau** [comment]
@vancura This only really works for that specific type of property. While we perhaps can be curated about property types we know about, we're looking for the non-curated experience. The user is going from a property set to null to creating a new instance of an object of some type, this is related to #116. Then with that instance, editing its properties which you have here. I'm not sure what "show most-used properties only" is, but we have no way of knowing that and can't implement such a feature.

**Comment by vancura** [comment]
> I'm not sure what "show most-used properties only" is, but we have no way of knowing that and can't implement such a feature.

It's the same feature as what VS has:

![screen recording 2018-02-08 at 11 38 54 am](https://user-images.githubusercontent.com/4982/35968608-b4761096-0cc4-11e8-886d-b67539843a9d.gif)

**Comment by vancura** [comment]
There are two states of that label:

1. The advanced content is collapsed:

![screenshot_2](https://user-images.githubusercontent.com/4982/35968818-32fe2570-0cc5-11e8-9aab-131020a701dc.png)

2. It's expanded:

![screenshot_3](https://user-images.githubusercontent.com/4982/35968822-391fa79e-0cc5-11e8-9c4a-90538c66b684.png)

**Comment by vancura** [comment]
> This only really works for that specific type of property. While we perhaps can be curated about property types we know about, we're looking for the non-curated experience. The user is going from a property set to null to creating a new instance of an object of some type, this is related to #116. Then with that instance, editing its properties which you have here. 

Then, let's have a more generic version:

<img width="408" alt="1 - mac object editor new 2x" src="https://user-images.githubusercontent.com/4982/35969192-5420d6fc-0cc6-11e8-8645-c3294abfa8c6.png">

<img width="408" alt="2 - mac object editor added 2x" src="https://user-images.githubusercontent.com/4982/35969195-570df822-0cc6-11e8-83f7-14bc341cc59e.png">

<img width="408" alt="3 - mac object editor added 2x-1" src="https://user-images.githubusercontent.com/4982/35969198-59df4aba-0cc6-11e8-89f5-d45b01e54464.png">

<img width="442" alt="4 - mac object editor added 2x-2" src="https://user-images.githubusercontent.com/4982/35969200-5c63697e-0cc6-11e8-92e8-0e810c3af95d.png">

Thoughts?

**Comment by ermau** [comment]
There are potentially 100s if not more items in the list, the VS version of this breaks it down by assembly and namespace for this reason, for some properties it could be any type in all of .NET.

**Comment by vancura** [comment]
I didn't have a better word for that, it's easy to rename based on the case.

**Comment by vancura** [comment]
If there's this number of items, we can use this approach, including tye type of the property (in the rectangle, inversed):

![](https://user-images.githubusercontent.com/4982/35865277-62471070-0b54-11e8-8caa-2285c51d95fd.png)

**Comment by vancura** [comment]
Design and discussion at https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/4252.
