### ISSUE TITLE
Int property is set as a long

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.PropertyEditing#174]
For my properties of type `int`, `SetValueAsync` sets them as a `ValueInfo<long>`.

Is this by chance expected behavior?

It doesn't really seem right, but if it's expected I'll need to make some changes on my side to accommodate.

**Comment by ermau** [comment]
This is expected, but not necessarily correct. Since we need to be able to do some basic math, we have to have concrete versions of the various numeric types, so I went for the widest types. You'll find that float also translates to double. It's perhaps not a big deal to keep the current approach and just copy/paste into the various individual types.

**Comment by BretJohnson** [comment]
I played around with doing the casting on my side, but don't think it's possible with it being a generic type.
I'll just wait for the real fix on the Proppy side. Or, failing that, we'll go with a different workaround.
