### ISSUE TITLE
Should have easy way to see property resource id

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.PropertyEditing#222]
In our current VSWin and VSMac Android Designer UI, and in Android Studio, when setting a property from a resource, the resource identifier itself (e.g. `@android:color/background_light`) is shown directly in the property panel UI.  Per @garuma, that's pretty useful, and it, again, is our current functionality.

Android Studio, for instance, does pretty good job of showing both the value and the resource identifier side by side, like here for for bool (checkbox) and color properties set from a resource:
![image](https://user-images.githubusercontent.com/245892/36520929-f3b34056-1761-11e8-9443-bbf638f5f535.png)

Whereas currently in Proppy, for most resource based properties the only way to see the resource identifier string is to bring up the resource picker dialog again and see what choice is selected by default.

While the Android Studio style UI is worth considering for the future, I'd propose we do this - which seems pretty useful and of relatively modest cost:  We add tooltip UI to Proppy property values, to support showing extra useful info. And have rules like these:

- For resource based property values, show the resource identifier string in the tooltip.
- For color properties, show the color hex value in the tooltip.  If a property is both resource based & a color property, show both the resource ID and color hex value, on separate lines (resource ID first).
- For custom expression properties, if the value in the custom expression is different than what's currently shown in the main proppy UI, then show the custom expression value in the tooltip.
- Later, for say binding properties, we can show e.g. binding text here too.  But the above 3 cases are the ones that we care about (I think) for Android.

cc: @vancura @bleroy

**Comment by vancura** [comment]
I would love to display both.

**Comment by garuma** [comment]
No matter the presentation, it should be easy and straightforward to see at a glance (and not behind multiple clicks) what the resource URL might be if one is set. Displaying both is a good option when feasible.

**Comment by JonDouglas** [comment]
Personally, I don't see tooltips being that useful for these items. For each of these scenarios, it seems like a "tooltip" should be replaced with a proper "Resource Manager UI".

- For resource based property values, show the resource identifier string in the tooltip.

This should already be the value, what does Proppy currently show? Do we have examples?

> Whereas currently in Proppy, for most resource based properties the only way to see the resource identifier string is to bring up the resource picker dialog again and see what choice is selected by default.

- For color properties, show the color hex value in the tooltip. If a property is both resource based & a color property, show both the resource ID and color hex value, on separate lines (resource ID first).
Show both when possible as the visualization makes it easy to know what that resource's value is from a glance.

It feels that this should be handled by a "resource manager UI" rather than the designer properties. Showing both the resource path and color picker preview sounds ideal. If the developer needs to change that resource in any fashion (such as changing the color, name, etc) it should override the resource and reference in the designer. How is this handled in Proppy?

- For custom expression properties, if the value in the custom expression is different than what's currently shown in the main proppy UI, then show the custom expression value in the tooltip.

Any examples on these in Proppy?

**Comment by alanmcgovern** [comment]
I think this would be a good thing to bring @chrisntr into!

**Comment by BretJohnson** [comment]
I agree that showing both side by side is better, UX wise, at least if there's enough space (which there generally is, except probably in the case of string resource values).
I just mentioned tooltips because:
- It seemed easier, in terms of dev cost, and thus maybe more likely to make it for 15.7
- It can be useful in some other contexts too (like see above).

In any case, we should feel free to do a UI spec here (e.g. of side by side).

**Comment by vancura** [comment]
What about this?

![untitled-1](https://user-images.githubusercontent.com/4982/36727273-f27b2ba4-1bbc-11e8-8ac6-1b699f54bfde.png)

**Comment by alanmcgovern** [comment]
I have a proposal - how about we consider this as an improvement which we should begin investigating after we ship V1 of proppy with VS 15.7.  We have had several calls for design/input at this point and we have specced out and implemented things as best we could based on the feedback which was provided. At some point we have to draw a line and say "enough is enough, we need to implement what we have and improve our customer's lives".

We can discuss further with Eric and see.

**Comment by chrisntr** [comment]
I didn't know this was something we were even thinking about for consideration for 15.7 but agreed on getting what we have shipped, and then we can seek feedback post release on the best way to handle this going forward in a future release.

**Comment by garuma** [comment]
By no means this is a blocker for shipping proppy.

That being said, it should still be considered a degradation of UX to have the resource URL hidden away behind a dialog (we might not have stressed it enough in the original design document which is our bad).

If it can be tackled in a non-invasive way for V1 great otherwise it should be among the first things to fix post-V1.

**Comment by ermau** [comment]
The resource name is displayed in the property button tooltip (we'll also need to make sure the accessibility text includes this information.)

Past that, I don't really see it as viable to show both. You can't really cram both the value and the resource name into these editors, @vancura 's examples demonstrate how easy it'll be to cut them off and don't even address confusing scenarios (what's a textbox show?) Past that it makes it immediately inconsistent and creates custom design and implementation work for _every_ editor specifically for Android.
