### ISSUE TITLE
Rectangle / Size / Point don't layout well on constrained sizes

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#518]
The spacing between the left and right sides almost seems fixed, it doesn't reduce it to try to fit when in a narrow layout.

**Comment by CartBlanche** [comment]
@vancura With the Rectangle / Size / Point controls on Mac, I thought the spec was to have them fixed size. Should the resize as per control width. Do they have a maximum and minimum size, if so, what should that be?

**Comment by vancura** [comment]
I wouldn't define any min or max, the panel itself helps in that: when the width is too low, all the controls look bad no matter what, and when it's really wide, all the controls should still look good (because of the contents alignment).

Also, if we say a control has a minimum width, what would happen when the panel is too narrow? Horizontal scroller?

**Comment by CartBlanche** [comment]
OK. So I'll constrain the right side control to the `Right` of the of the Left control, so it stays the right distance. Just need to work out how to keep the X/Y etc labels constrained in the right places during resizes.
